# Generated by Django 3.2.13 on 2024-07-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('deportes', '0001_initial'),
        ('categorias', '0001_initial'),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.deporte')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.instalacion')),
            ],
        ),
    ]
