# Generated by Django 3.2.13 on 2024-07-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federaciones', '0001_initial'),
        ('deportes', '0001_initial'),
        ('entrenadores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.deporte')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenadores.entrenador')),
                ('federacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federaciones.federacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
